fail_fast: true

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:

    # git
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: destroyed-symlinks
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: forbid-new-submodules

    # python
    - id: check-ast
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: debug-statements
    - id: name-tests-test

    # json
    - id: check-json

    # yaml
    - id: check-yaml

    # invalid files
    - id: check-toml
    - id: check-xml

    # misc
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: no-commit-to-branch

- repo: https://github.com/tomhoover/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: forbid-binary
    - id: script-must-have-extension
    - id: shellcheck

- repo: https://github.com/tomhoover/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: script-must-have-extension
      name: Local policy is to use .sh extension for shell scripts
      types: [shell, executable]

# python

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3.11

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
    - id: pylint
      args: [--disable=all, --enable=unused-import]
