---
# tasks file for pihole_keepalived

- name: Is pihole binary installed?
  ansible.builtin.stat:
    path: '/usr/local/bin/pihole'
  register: p
- ansible.builtin.set_fact:
    pihole_installed: '{{ p.stat.exists|default(false) }}'

- name: Is pihole official docker image installed?
  ansible.builtin.shell: "docker ps | grep pihole/pihole | sed -e 's/ .*//'"
  register: d
- ansible.builtin.shell: "docker exec {{ d.stdout }} pihole"
  register: p
  ignore_errors: true
- ansible.builtin.set_fact:
    docker_pihole_installed: '{{ p.rc==0|default(false) }}'

- name: Not installed msg
  ansible.builtin.fail:
    msg: "ERROR: pihole must be installed before tomhoover.pihole_keepalived!"
  when:
    - not pihole_installed
    - not docker_pihole_installed

- name: Install packages
  ansible.builtin.apt:
    pkg:
    - keepalived
    - libipset11
  when: ( pihole_installed or docker_pihole_installed ) and ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: Install packages
  ansible.builtin.apt:
    pkg:
    - keepalived
    - libipset13
  when: ( pihole_installed or docker_pihole_installed ) and ansible_distribution == "Debian" and ( ansible_distribution_release == "bullseye" or ansible_distribution_release == "bookworm" )

- name: Copy keepalived.conf to /etc/keepalived/
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    mode: 0644
  notify:
    - Restart keepalived
  when: pihole_installed or docker_pihole_installed
