---
# tasks file for pihole_keepalived

- name: Install packages
  ansible.builtin.apt:
    pkg:
    - keepalived
    - libipset11
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: Install packages
  ansible.builtin.apt:
    pkg:
    - keepalived
    - libipset13
  when: ansible_distribution == "Debian" and ( ansible_distribution_release == "bullseye" or ansible_distribution_release == "bookworm" )

- name: Copy keepalived.conf to /etc/keepalived/
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    mode: 0644
  notify:
    - Restart keepalived
